### ISSUE TITLE
Multitroid crash on devices that don't support custom palettes shader.

### ISSUE THREAD

**Issue by Jesright73** [Hornoads/AM2R-The-Horde-Multitroid#12]
When commits were manually pulled from 1.5.5 to Horde, the `global.shaders_compiled` check was removed from the script `draw_character`.

**To Reproduce**
play multitroid on a device that doesn't support the palette shader

**Media**
![image](https://user-images.githubusercontent.com/79653967/160197583-9f14976e-e6f8-4151-8aca-b713259d7d6d.png)

**Platform (please complete the following information):**
any that doesn't support custom shaders

**Game Version:**
Horde v1 PR

**Comment by Miepee** [comment]
Fixed in 1.1 release
