### ISSUE TITLE
Genesis doesn't respawn or drop item if player dies

### ISSUE THREAD

**Issue by Jesright73** [Hornoads/AM2R-The-Horde-Multitroid#13]
**To Reproduce**

1. Join a multitroid session with Fusion mode
2. Kill Genny
3. Die to the Core X
4. Genny no longer respawns, and core-x doesn't show up to give item

![image](https://user-images.githubusercontent.com/79653967/160224106-4b235ddb-f716-43c1-8b7d-dda3214c6e90.png)

**Game Version:**
Horde v1 PR

**Additional context**
Caused by core-x phases syncing in multitroid, but the Genesis trigger global.event check isn't set to check for Core-X still alive.

**Comment by Miepee** [comment]
@Jesright73 was this fixed by 1.1?
> Genesis boss no longer clips out of bounds

and/or

> Proper boss syncing in multitroid
