### ISSUE TITLE
CRASH: Unable to load Autohorde alarm

### ISSUE THREAD

**Issue by DodoBirby** [Hornoads/AM2R-The-Horde-Multitroid#3]
**Describe the bug**
Game crashed when the a5 zeta room auto H was activated

**Expected behavior**
Not crashing

 OS: [Windows
 

**Game Version:**
The Horde 1.0

**Comment by DodoBirby** [comment]
ERROR!!! :: ############################################################################################
FATAL ERROR in
action number 1
of Alarm Event for alarm 0
for object oAutoHorde:


Unable to find any instance for object index '550376'
at gml_Object_oAutoHorde_Alarm_0_9799
############################################################################################

**Comment by Jesright73** [comment]
This occurred when the AutoHorde was hit by an EMP explosion while in the air.
Is possible that the alarm for jumping continued ticking after the AutoHorde was disabled.

**Comment by Jesright73** [comment]
an attempt to fix has been applied to the dev build
