### ISSUE TITLE
Easy way to get OOB

### ISSUE THREAD

**Issue by Miepee** [Hornoads/AM2R-The-Horde-Multitroid#4]
**Describe the bug**
Easy way to get OOB in GT trying to get to the top alpha

**To Reproduce**
Spiderball through here
![image](https://user-images.githubusercontent.com/38186597/156541247-258fb091-491e-4007-8818-a16c5701cd88.png)

**Expected behavior**
player should never get OoB

**Media**
![image](https://user-images.githubusercontent.com/38186597/156541274-a117d945-2ebd-4c34-9eee-597b05fe247a.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Version: 10

**Game Version:**
1.0

**Additional context**
Add any other context about the problem here, including custom settings in `modifiers.ini`.

**Comment by Jesright73** [comment]
Duplicate of #2

**Comment by Miepee** [comment]
Must've missed that.
